name: base
matches:
  - trigger: ":cc"
    replace: "«$|$»"
    force_clipboard: true

  - trigger: ":ca"
    replace: "«"
    force_clipboard: true

  - trigger: ":cc"
    replace: "»"
    force_clipboard: true

  - trigger: ":ang"
    replace: "<$|$>"
    force_clipboard: true

  - trigger: ":ana"
    replace: "<"
    force_clipboard: true

  - trigger: ":anc"
    replace: ">"
    force_clipboard: true

  - trigger: ":fle"
    replace: "-->"
    force_clipboard: true

  - trigger: ":ffl"
    replace: "=>"
    force_clipboard: true

  - trigger: ":sect"
    replace: "§ "
    force_clipboard: true

  # Markdown syntax
  - trigger: "mdcm"
    replace: "<!--$|$-->"
    force_clipboard: true

  - trigger: "mdcd"
    replace: "```\n$|$\n```"
    force_clipboard: true

  - trigger: "mdjs"
    replace: "```js\n$|$\n```"
    force_clipboard: true

  # PERSONAL
  - trigger: ":mml"
    replace: "s.abrahambh@gmail.com"
    force_clipboard: true

  - trigger: ":wml"
    replace: "hi@sergio-barrera.com"
    force_clipboard: true

  - trigger: ":bmac"
    replace: "https://buymeacoffee.com/sabhz"

  - trigger: ":lnkd"
    replace: "https://www.linkedin.com/in/sergio-barrera-1b9110323/?locale=en_US"
    force_clipboard: true

  - trigger: ":mweb"
    replace: "https://sabhz.com/"

  - trigger: ":wweb"
    replace: "https://sergio-barrera.com"

  - trigger: ":gh"
    replace: "https://github.com/abrahambahez"

  - trigger: ":orcid"
    replace: "0009-0002-1457-5203"

  - trigger: ":sb"
    replace: "Sergio Barrera"
    force_clipboard: true

  # Common phrases

  # Dynamic
  - trigger: "dt "
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: "dte "
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: "tm "
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%H:%M"

  - trigger: "dtm "
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%dT%H:%M"

  - trigger: "dtid "
    replace: "{{date_id}}"
    vars:
      - name: date_id
        type: date
        params:
          format: "%Y%m%d%H%M"

